version: '3'

services:
  mysql:
    image: mysql:5.7.22 
    volumes:
      - ./mysql_host_dir:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=mysqladmin
      - MYSQL_DATABASE=traffic

  grafana:
    image: grafana/grafana:5.1.3
    volumes:
      - ./grafana_host_dir:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - mysql

  py-darknet:
    build: .
    tty: true
    depends_on:
      - mysql

